### ISSUE TITLE
Include more heading levels in TOC

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#70]
This is deactivated in CSS. The elements are there. 

```css
.toc > ul > li ul {
    display: none;
}
```

Just change the styling.
